// my-dashboard/src/pages/Login.jsx
import React from "react";
import { Link } from "react-router-dom";

const Login = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-sm">
        <h2 className="text-2xl font-bold mb-4 text-center">Login</h2>
        <form className="space-y-4">
          <input
            type="email"
            placeholder="Email"
            className="w-full p-2 border border-gray-300 rounded"
          />
          <input
            type="password"
            placeholder="Password"
            className="w-full p-2 border border-gray-300 rounded"
          />
          <button
            type="submit"
            className="w-full bg-blue-500 text-white p-2 rounded hover:bg-blue-600 cursor-pointer"
          >
            Login
          </button>
        </form>
        <p className="text-center mt-4">
          Don’t have an account?{" "}
          <Link to="/signup" className="text-blue-500 hover:underline">
            Signup
          </Link>
        </p>
      </div>
    </div>
  );
};

export default Login;

// eCommerce-nuxt/pages/login.vue
<template>
  <div class="min-h-screen bg-gray-100 flex items-center justify-center">
    <div class="max-w-md w-full bg-white rounded-lg shadow-md p-8">
      <h2 class="text-2xl font-bold text-center mb-6">Login</h2>
      
      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="block text-gray-700 mb-2">Email</label>
          <input 
            type="email" 
            v-model="email" 
            required
            class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-blue-500"
          >
        </div>
        
        <div>
          <label class="block text-gray-700 mb-2">Password</label>
          <input 
            type="password" 
            v-model="password" 
            required
            class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:border-blue-500"
          >
        </div>
        
        <button 
          type="submit"
          class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition"
        >
          Login
        </button>
      </form>
      
      <p class="mt-4 text-center text-gray-600">
        Don't have an account? 
        <NuxtLink to="/register" class="text-blue-600 hover:text-blue-800">
          Register
        </NuxtLink>
      </p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      email: '',
      password: ''
    }
  },
  methods: {
    handleLogin() {
      // Simulate login - in a real app, this would call an API
      const user = {
        email: this.email,
        id: Date.now()
      }
      localStorage.setItem('user', JSON.stringify(user))
      this.$router.push('/')
    }
  }
}
</script>
